<?php
/*
Template Name: search
*/
?>
<?php get_header(); ?>
<main>
    <section class="wrapper">
        <h2 class="section-header">Подбор электродвигателя</h2>
        <div class="container">
            <div class="search-container">
                <div class="tabs-container">
                    <ul class="tabs">
                        <li class="tab-item active">IM1001(лапы)</li>
                        <li class="tab-item">IM2001(фланец+лапы)</li>
                        <li class="tab-item">IM3001(фланец)</li>
                    </ul>
                    <div class="tab-picture">
                        <img id="tab-picture" src="<?=DS_ROOT . '/img/search/im1001.gif' ?>" alt="IM1001(лапы)">
                    </div>
                </div>
                <div class="table-container">
                    <table class="search-table" width="100%">
                        <tbody>
                        <tr>
                            <th><strong>Эл.двигатель <br></strong></th>
                            <th><strong>Число полюсов</strong></th>
                            <th colspan="16" align="center"><strong>Размеры, мм</strong></th>
                        </tr>
                        <tr>
                            <th colspan="2">&nbsp;</th>
                            <th>l30</th>
                            <th>h31</th>
                            <th>d24</th>
                            <th>l1</th>
                            <th>l10</th>
                            <th>l31</th>
                            <th>d1</th>
                            <th>d10</th>
                            <th>d20</th>
                            <th>d22</th>
                            <th>d25</th>
                            <th>b10</th>
                            <th>n</th>
                            <th>h</th>
                            <th>h5</th>
                            <th>b1</th>
                        </tr>
                        <tr>
                            <td>АИР 56 А, В</td>
                            <td>2;4</td>
                            <td>218</td>
                            <td>148</td>
                            <td>140</td>
                            <td>23</td>
                            <td>71</td>
                            <td>36</td>
                            <td>11</td>
                            <td>5,8</td>
                            <td>115</td>
                            <td>10</td>
                            <td>95</td>
                            <td>90</td>
                            <td>4</td>
                            <td>56</td>
                            <td>12,5</td>
                            <td>4</td>
                        </tr>
                        <tr>
                            <td>АИР 63 А, В</td>
                            <td>2;4</td>
                            <td>237</td>
                            <td>161</td>
                            <td>160</td>
                            <td>30</td>
                            <td>80</td>
                            <td>40</td>
                            <td>14</td>
                            <td>7</td>
                            <td>130</td>
                            <td>10</td>
                            <td>110</td>
                            <td>100</td>
                            <td>4</td>
                            <td>63</td>
                            <td>16</td>
                            <td>5</td>
                        </tr>
                        <tr>
                            <td>АИР 71 А, В</td>
                            <td>2;4;6</td>
                            <td>273</td>
                            <td>188</td>
                            <td>200</td>
                            <td>40</td>
                            <td>90</td>
                            <td>45</td>
                            <td>19</td>
                            <td>7</td>
                            <td>165</td>
                            <td>12</td>
                            <td>130</td>
                            <td>112</td>
                            <td>4</td>
                            <td>71</td>
                            <td>21,5</td>
                            <td>6</td>
                        </tr>
                        <tr>
                            <td>АИР 80 А</td>
                            <td>2;4;6</td>
                            <td>300</td>
                            <td>207</td>
                            <td>200</td>
                            <td>50</td>
                            <td>100</td>
                            <td>50</td>
                            <td>22</td>
                            <td>10</td>
                            <td>165</td>
                            <td>11</td>
                            <td>130</td>
                            <td>125</td>
                            <td>4</td>
                            <td>80</td>
                            <td>24,5</td>
                            <td>6</td>
                        </tr>
                        <tr>
                            <td>АИР 80 В</td>
                            <td>2;4;6</td>
                            <td>320</td>
                            <td>207</td>
                            <td>200</td>
                            <td>50</td>
                            <td>100</td>
                            <td>50</td>
                            <td>22</td>
                            <td>10</td>
                            <td>165</td>
                            <td>11</td>
                            <td>130</td>
                            <td>125</td>
                            <td>4</td>
                            <td>80</td>
                            <td>24,5</td>
                            <td>6</td>
                        </tr>
                        <tr>
                            <td>АИР 90 L</td>
                            <td>2;4;6</td>
                            <td>350</td>
                            <td>217</td>
                            <td>250</td>
                            <td>50</td>
                            <td>125</td>
                            <td>56</td>
                            <td>24</td>
                            <td>10</td>
                            <td>215</td>
                            <td>14</td>
                            <td>180</td>
                            <td>140</td>
                            <td>4</td>
                            <td>90</td>
                            <td>27</td>
                            <td>8</td>
                        </tr>
                        <tr>
                            <td>АИР 100 S</td>
                            <td>2;4</td>
                            <td>376</td>
                            <td>227</td>
                            <td>250</td>
                            <td>60</td>
                            <td>112</td>
                            <td>63</td>
                            <td>28</td>
                            <td>12</td>
                            <td>215</td>
                            <td>14</td>
                            <td>180</td>
                            <td>160</td>
                            <td>4</td>
                            <td>100</td>
                            <td>31</td>
                            <td>8</td>
                        </tr>
                        <tr>
                            <td>АИР 100 L</td>
                            <td>2;4;6</td>
                            <td>420</td>
                            <td>277</td>
                            <td>250</td>
                            <td>60</td>
                            <td>140</td>
                            <td>63</td>
                            <td>28</td>
                            <td>12</td>
                            <td>215</td>
                            <td>14</td>
                            <td>180</td>
                            <td>160</td>
                            <td>4</td>
                            <td>100</td>
                            <td>31</td>
                            <td>8</td>
                        </tr>
                        <tr>
                            <td>АИР 112 М</td>
                            <td>2; 4; 6; 8</td>
                            <td>475</td>
                            <td>297</td>
                            <td>300</td>
                            <td>80</td>
                            <td>140</td>
                            <td>70</td>
                            <td>32</td>
                            <td>12</td>
                            <td>265</td>
                            <td>14</td>
                            <td>230</td>
                            <td>190</td>
                            <td>4</td>
                            <td>112</td>
                            <td>35</td>
                            <td>10</td>
                        </tr>
                        <tr>
                            <td>АИР 132 S</td>
                            <td>4; 6; 8</td>
                            <td>510</td>
                            <td>345</td>
                            <td>350</td>
                            <td>80</td>
                            <td>140</td>
                            <td>89</td>
                            <td>38</td>
                            <td>12</td>
                            <td>300</td>
                            <td>19</td>
                            <td>250</td>
                            <td>216</td>
                            <td>4</td>
                            <td>132</td>
                            <td>41</td>
                            <td>10</td>
                        </tr>
                        <tr>
                            <td>АИР 132 М</td>
                            <td>2; 4; 6; 8</td>
                            <td>498</td>
                            <td>325</td>
                            <td>350</td>
                            <td>80</td>
                            <td>178</td>
                            <td>89</td>
                            <td>38</td>
                            <td>12</td>
                            <td>300</td>
                            <td>19</td>
                            <td>250</td>
                            <td>216</td>
                            <td>4</td>
                            <td>132</td>
                            <td>41</td>
                            <td>10</td>
                        </tr>
                        <tr>
                            <td>АИР 160 S</td>
                            <td>2</td>
                            <td>625</td>
                            <td>435</td>
                            <td>350</td>
                            <td>110</td>
                            <td>178</td>
                            <td>108</td>
                            <td>42</td>
                            <td>15</td>
                            <td>300</td>
                            <td>19</td>
                            <td>250</td>
                            <td>254</td>
                            <td>4</td>
                            <td>160</td>
                            <td>45</td>
                            <td>12</td>
                        </tr>
                        <tr>
                            <td>АИР 160 S</td>
                            <td>4; 6; 8</td>
                            <td>625</td>
                            <td>435</td>
                            <td>350</td>
                            <td>110</td>
                            <td>178</td>
                            <td>108</td>
                            <td>48</td>
                            <td>15</td>
                            <td>300</td>
                            <td>19</td>
                            <td>250</td>
                            <td>254</td>
                            <td>4</td>
                            <td>160</td>
                            <td>51,5</td>
                            <td>14</td>
                        </tr>
                        <tr>
                            <td>АИР 160 М</td>
                            <td>2</td>
                            <td>670</td>
                            <td>435</td>
                            <td>350</td>
                            <td>110</td>
                            <td>210</td>
                            <td>108</td>
                            <td>42</td>
                            <td>15</td>
                            <td>300</td>
                            <td>19</td>
                            <td>250</td>
                            <td>254</td>
                            <td>4</td>
                            <td>160</td>
                            <td>45</td>
                            <td>12</td>
                        </tr>
                        <tr>
                            <td>АИР 160 М</td>
                            <td>4; 6; 8</td>
                            <td>670</td>
                            <td>435</td>
                            <td>350</td>
                            <td>110</td>
                            <td>210</td>
                            <td>108</td>
                            <td>48</td>
                            <td>15</td>
                            <td>300</td>
                            <td>19</td>
                            <td>250</td>
                            <td>254</td>
                            <td>4</td>
                            <td>160</td>
                            <td>51,5</td>
                            <td>14</td>
                        </tr>
                        <tr>
                            <td>АИР 180 S</td>
                            <td>2</td>
                            <td>700</td>
                            <td>460</td>
                            <td>400</td>
                            <td>110</td>
                            <td>203</td>
                            <td>121</td>
                            <td>48</td>
                            <td>15</td>
                            <td>350</td>
                            <td>19</td>
                            <td>300</td>
                            <td>279</td>
                            <td>4</td>
                            <td>180</td>
                            <td>51,5</td>
                            <td>14</td>
                        </tr>
                        <tr>
                            <td>АИР 180 S</td>
                            <td>4</td>
                            <td>700</td>
                            <td>460</td>
                            <td>400</td>
                            <td>110</td>
                            <td>203</td>
                            <td>121</td>
                            <td>55</td>
                            <td>15</td>
                            <td>350</td>
                            <td>19</td>
                            <td>300</td>
                            <td>279</td>
                            <td>4</td>
                            <td>180</td>
                            <td>59</td>
                            <td>16</td>
                        </tr>
                        <tr>
                            <td>АИР 180 М</td>
                            <td>2</td>
                            <td>740</td>
                            <td>460</td>
                            <td>400</td>
                            <td>110</td>
                            <td>241</td>
                            <td>121</td>
                            <td>48</td>
                            <td>15</td>
                            <td>350</td>
                            <td>19</td>
                            <td>300</td>
                            <td>279</td>
                            <td>4</td>
                            <td>180</td>
                            <td>51,5</td>
                            <td>14</td>
                        </tr>
                        <tr>
                            <td>АИР 180 М</td>
                            <td>4; 6; 8</td>
                            <td>740</td>
                            <td>460</td>
                            <td>400</td>
                            <td>110</td>
                            <td>241</td>
                            <td>121</td>
                            <td>55</td>
                            <td>15</td>
                            <td>350</td>
                            <td>19</td>
                            <td>300</td>
                            <td>279</td>
                            <td>4</td>
                            <td>180</td>
                            <td>59</td>
                            <td>16</td>
                        </tr>
                        <tr>
                            <td>АИР 200 М</td>
                            <td>2</td>
                            <td>775</td>
                            <td>505</td>
                            <td>450</td>
                            <td>110</td>
                            <td>267</td>
                            <td>133</td>
                            <td>55</td>
                            <td>19</td>
                            <td>400</td>
                            <td>19</td>
                            <td>350</td>
                            <td>318</td>
                            <td>8</td>
                            <td>200</td>
                            <td>59</td>
                            <td>16</td>
                        </tr>
                        <tr>
                            <td>АИР 200 М</td>
                            <td>4; 6; 8</td>
                            <td>775</td>
                            <td>505</td>
                            <td>450</td>
                            <td>140</td>
                            <td>267</td>
                            <td>133</td>
                            <td>60</td>
                            <td>19</td>
                            <td>400</td>
                            <td>19</td>
                            <td>350</td>
                            <td>318</td>
                            <td>8</td>
                            <td>200</td>
                            <td>64</td>
                            <td>18</td>
                        </tr>
                        <tr>
                            <td>АИР 200 L</td>
                            <td>2</td>
                            <td>775</td>
                            <td>505</td>
                            <td>450</td>
                            <td>110</td>
                            <td>305</td>
                            <td>133</td>
                            <td>55</td>
                            <td>19</td>
                            <td>400</td>
                            <td>19</td>
                            <td>350</td>
                            <td>318</td>
                            <td>8</td>
                            <td>200</td>
                            <td>59</td>
                            <td>16</td>
                        </tr>
                        <tr>
                            <td>АИР 200 L</td>
                            <td>4; 6; 8</td>
                            <td>775</td>
                            <td>505</td>
                            <td>450</td>
                            <td>140</td>
                            <td>305</td>
                            <td>133</td>
                            <td>60</td>
                            <td>19</td>
                            <td>400</td>
                            <td>19</td>
                            <td>350</td>
                            <td>318</td>
                            <td>8</td>
                            <td>200</td>
                            <td>64</td>
                            <td>18</td>
                        </tr>
                        <tr>
                            <td>АИР 225 М</td>
                            <td>2</td>
                            <td>835</td>
                            <td>535</td>
                            <td>550</td>
                            <td>110</td>
                            <td>311</td>
                            <td>149</td>
                            <td>55</td>
                            <td>19</td>
                            <td>500</td>
                            <td>19</td>
                            <td>450</td>
                            <td>356</td>
                            <td>8</td>
                            <td>225</td>
                            <td>59</td>
                            <td>16</td>
                        </tr>
                        <tr>
                            <td>АИР 225 М</td>
                            <td>4; 6; 8</td>
                            <td>865</td>
                            <td>535</td>
                            <td>550</td>
                            <td>140</td>
                            <td>311</td>
                            <td>149</td>
                            <td>65</td>
                            <td>19</td>
                            <td>500</td>
                            <td>19</td>
                            <td>450</td>
                            <td>356</td>
                            <td>8</td>
                            <td>225</td>
                            <td>69</td>
                            <td>18</td>
                        </tr>
                        <tr>
                            <td>АИР 250 S</td>
                            <td>2</td>
                            <td>880</td>
                            <td>590</td>
                            <td>550</td>
                            <td>140</td>
                            <td>311</td>
                            <td>168</td>
                            <td>65</td>
                            <td>24</td>
                            <td>500</td>
                            <td>19</td>
                            <td>450</td>
                            <td>406</td>
                            <td>8</td>
                            <td>250</td>
                            <td>69</td>
                            <td>18</td>
                        </tr>
                        <tr>
                            <td>АИР 250 S</td>
                            <td>4; 6; 8</td>
                            <td>880</td>
                            <td>590</td>
                            <td>550</td>
                            <td>140</td>
                            <td>311</td>
                            <td>168</td>
                            <td>75</td>
                            <td>24</td>
                            <td>500</td>
                            <td>19</td>
                            <td>450</td>
                            <td>406</td>
                            <td>8</td>
                            <td>250</td>
                            <td>79,5</td>
                            <td>20</td>
                        </tr>
                        <tr>
                            <td>АИР 250 М</td>
                            <td>2</td>
                            <td>905</td>
                            <td>590</td>
                            <td>550</td>
                            <td>140</td>
                            <td>349</td>
                            <td>168</td>
                            <td>65</td>
                            <td>24</td>
                            <td>500</td>
                            <td>19</td>
                            <td>450</td>
                            <td>406</td>
                            <td>8</td>
                            <td>250</td>
                            <td>69</td>
                            <td>18</td>
                        </tr>
                        <tr>
                            <td>АИР 250 М</td>
                            <td>4; 6; 8</td>
                            <td>905</td>
                            <td>590</td>
                            <td>550</td>
                            <td>140</td>
                            <td>349</td>
                            <td>168</td>
                            <td>75</td>
                            <td>24</td>
                            <td>500</td>
                            <td>19</td>
                            <td>450</td>
                            <td>406</td>
                            <td>8</td>
                            <td>250</td>
                            <td>79,5</td>
                            <td>20</td>
                        </tr>
                        <tr>
                            <td>АИР 280 S</td>
                            <td>2</td>
                            <td>1110</td>
                            <td>660</td>
                            <td>660</td>
                            <td>140</td>
                            <td>368</td>
                            <td>190</td>
                            <td>70</td>
                            <td>24</td>
                            <td>600</td>
                            <td>24</td>
                            <td>550</td>
                            <td>457</td>
                            <td>8</td>
                            <td>280</td>
                            <td>74,5</td>
                            <td>20</td>
                        </tr>
                        <tr>
                            <td>АИР 280 S</td>
                            <td>4,6,8</td>
                            <td>1110</td>
                            <td>660</td>
                            <td>660</td>
                            <td>170</td>
                            <td>368</td>
                            <td>190</td>
                            <td>80</td>
                            <td>24</td>
                            <td>600</td>
                            <td>24</td>
                            <td>550</td>
                            <td>457</td>
                            <td>8</td>
                            <td>280</td>
                            <td>85</td>
                            <td>22</td>
                        </tr>
                        <tr>
                            <td>АИР 280 М</td>
                            <td>2</td>
                            <td>1180</td>
                            <td>660</td>
                            <td>660</td>
                            <td>140</td>
                            <td>419</td>
                            <td>190</td>
                            <td>70</td>
                            <td>24</td>
                            <td>600</td>
                            <td>24</td>
                            <td>550</td>
                            <td>457</td>
                            <td>8</td>
                            <td>280</td>
                            <td>74,5</td>
                            <td>20</td>
                        </tr>
                        <tr>
                            <td>АИР 280 М</td>
                            <td>4,6,8</td>
                            <td>1180</td>
                            <td>660</td>
                            <td>660</td>
                            <td>170</td>
                            <td>419</td>
                            <td>190</td>
                            <td>80</td>
                            <td>24</td>
                            <td>600</td>
                            <td>24</td>
                            <td>550</td>
                            <td>457</td>
                            <td>8</td>
                            <td>280</td>
                            <td>85</td>
                            <td>22</td>
                        </tr>
                        <tr>
                            <td>АИР 315 S</td>
                            <td>2</td>
                            <td>1290</td>
                            <td>765</td>
                            <td>660</td>
                            <td>140</td>
                            <td>406</td>
                            <td>216</td>
                            <td>75</td>
                            <td>28</td>
                            <td>600</td>
                            <td>24</td>
                            <td>550</td>
                            <td>508</td>
                            <td>8</td>
                            <td>315</td>
                            <td>79,5</td>
                            <td>20</td>
                        </tr>
                        <tr>
                            <td>АИР 315 S</td>
                            <td>4,6,8,10</td>
                            <td>1290</td>
                            <td>765</td>
                            <td>660</td>
                            <td>170</td>
                            <td>406</td>
                            <td>216</td>
                            <td>90</td>
                            <td>28</td>
                            <td>600</td>
                            <td>24</td>
                            <td>550</td>
                            <td>508</td>
                            <td>8</td>
                            <td>315</td>
                            <td>95</td>
                            <td>25</td>
                        </tr>
                        <tr>
                            <td>АИР 315 М</td>
                            <td>2</td>
                            <td>1325</td>
                            <td>765</td>
                            <td>660</td>
                            <td>140</td>
                            <td>457</td>
                            <td>216</td>
                            <td>75</td>
                            <td>28</td>
                            <td>600</td>
                            <td>24</td>
                            <td>550</td>
                            <td>508</td>
                            <td>8</td>
                            <td>315</td>
                            <td>79,5</td>
                            <td>20</td>
                        </tr>
                        <tr>
                            <td>АИР 315 М</td>
                            <td>4,6,8,10</td>
                            <td>1325</td>
                            <td>765</td>
                            <td>660</td>
                            <td>170</td>
                            <td>457</td>
                            <td>216</td>
                            <td>90</td>
                            <td>28</td>
                            <td>600</td>
                            <td>24</td>
                            <td>550</td>
                            <td>508</td>
                            <td>8</td>
                            <td>315</td>
                            <td>95</td>
                            <td>25</td>
                        </tr>
                        <tr>
                            <td>АИР 355 S, M</td>
                            <td>2</td>
                            <td>1495</td>
                            <td>1010</td>
                            <td>800</td>
                            <td>170</td>
                            <td>500|560</td>
                            <td>254</td>
                            <td>85</td>
                            <td>28-6</td>
                            <td>740</td>
                            <td>24</td>
                            <td>680</td>
                            <td>610</td>
                            <td>&nbsp;</td>
                            <td>355</td>
                            <td>90</td>
                            <td>22</td>
                        </tr>
                        <tr>
                            <td>АИР 355 S, M</td>
                            <td>4,6,8,10</td>
                            <td>1525</td>
                            <td>1010</td>
                            <td>800</td>
                            <td>210</td>
                            <td>500|560</td>
                            <td>254</td>
                            <td>100</td>
                            <td>28-6</td>
                            <td>740</td>
                            <td>24</td>
                            <td>680</td>
                            <td>610</td>
                            <td>&nbsp;</td>
                            <td>355</td>
                            <td>106</td>
                            <td>28</td>
                        </tr>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </section>
</main>
<?php get_footer(); ?>